name: Workflow for testing ping action
on: push

jobs:
  build:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: Leocardoso94/is-my-site-up@v0.2.1
        with:
          site: "kylz.nl"
